# Generated by Django 4.1.3 on 2022-11-14 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemaDeControlApp", "0002_alter_producto_fecha_de_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="fecha_de_creacion",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Fecha de creacion"
            ),
        ),
    ]
