# Generated by Django 4.1.3 on 2022-11-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemaDeControlApp", "0004_rename_producto_devoluciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devoluciones",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="devoluciones",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="devolucion", verbose_name="Imagen"
            ),
        ),
    ]
