# Generated by Django 4.1.3 on 2022-11-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemaDeControlApp", "0006_alter_devoluciones_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devoluciones",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="captura_imagen_para_registro",
                verbose_name="Imagen",
            ),
        ),
    ]
