# Generated by Django 4.1.3 on 2022-11-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemaDeControlApp", "0007_alter_devoluciones_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devoluciones",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="devolucion_captura",
                verbose_name="Imagen",
            ),
        ),
    ]
