# Generated by Django 4.1.3 on 2022-11-19 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sistemaDeControlApp", "0009_alter_devoluciones_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devoluciones",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="devoluciones",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="devoluciones",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="devoluciones",
            name="precio",
        ),
        migrations.RemoveField(
            model_name="devoluciones",
            name="stock",
        ),
        migrations.AddField(
            model_name="devoluciones",
            name="cantidad_devuelta",
            field=models.IntegerField(default=0, verbose_name="Cantidad"),
        ),
        migrations.AddField(
            model_name="devoluciones",
            name="distribuidor_a_cargo",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Distribuidor"
            ),
        ),
        migrations.AddField(
            model_name="devoluciones",
            name="nombre_del_cliente",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, verbose_name="Cliente"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="devoluciones",
            name="producto_devuelto",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="Producto"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="devoluciones",
            name="vendedor",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=50,
                verbose_name="Vendedor",
            ),
            preserve_default=False,
        ),
    ]
