# Generated by Django 4.1.3 on 2022-11-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemaDeControlApp", "0011_alter_devoluciones_distribuidor_a_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devoluciones",
            name="distribuidor_a_cargo",
            field=models.TextField(max_length=100, verbose_name="Distribuidor"),
        ),
        migrations.AlterField(
            model_name="devoluciones",
            name="vendedor",
            field=models.TextField(max_length=50, verbose_name="Vendedor"),
        ),
    ]
