# Generated by Django 4.1.3 on 2022-11-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemaDeControlApp", "0013_alter_devoluciones_cantidad_devuelta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devoluciones",
            name="distribuidor_a_cargo",
            field=models.CharField(max_length=50, verbose_name="Distribuidor"),
        ),
        migrations.AlterField(
            model_name="devoluciones",
            name="producto_devuelto",
            field=models.CharField(max_length=50, verbose_name="Producto"),
        ),
        migrations.AlterField(
            model_name="devoluciones",
            name="vendedor",
            field=models.CharField(max_length=50, verbose_name="Vendedor"),
        ),
    ]
