# Generated by Django 4.1.3 on 2022-11-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDeControlApp', '0014_alter_devoluciones_distribuidor_a_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('Supermercado', 'SUPERMERCADO'), ('Minimarket', 'MINIMARKET'), ('Estacion de servicio', 'ESTACION DE SERVICIO'), ('Otro', 'OTRO')], default='Araucania', max_length=100, verbose_name='Tipo de cliente')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('linea', models.CharField(max_length=50, verbose_name='Linea de producto')),
                ('precio_unitario', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['linea'],
            },
        ),
    ]
