# Generated by Django 4.1.3 on 2022-11-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDeControlApp', '0015_cliente_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('vendedor', models.CharField(max_length=100, verbose_name='Vendedor')),
                ('distribuidora', models.CharField(choices=[('Arica y Parinacota', 'ARICA Y PARINACOTA'), ('Tarapaca', 'TARAPACA'), ('Antofagasta', 'ANTOFAGASTA'), ('Atacama', 'ATACAMA'), ('Coquimbo', 'COQUIMBO'), ('Valparaiso', 'VALPARAISO'), ('Region Metropolitana', 'REGION METROPOLITANA'), ('Libertador Gral. Bernardo OHiggings', 'LIBERTADOR GRAL. BERNARDO OHIGGINGS'), ('Maule', 'MAULE'), ('Nuble', 'NUBLE'), ('Bio-Bio', 'BIO-BIO'), ('Araucania', 'ARAUCANIA'), ('Rios', 'RIOS'), ('Lagos', 'LAGOS'), ('Aysen', 'AYSEN'), ('Magallanes y de la Antartica Chilena', 'MAGALLANES Y DE LA ANTARTICA CHILENA')], max_length=100, verbose_name='Distribuidora')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemaDeControlApp.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemaDeControlApp.producto')),
            ],
            options={
                'ordering': ['distribuidora'],
            },
        ),
    ]
