# Generated by Django 4.1.3 on 2022-11-28 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDeControlApp', '0016_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creacion'),
        ),
    ]
