# Generated by Django 4.1.3 on 2022-11-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDeControlApp', '0017_devolucion_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devoluciones',
        ),
    ]
