# Generated by Django 4.1.3 on 2022-12-03 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDeControlApp', '0018_delete_devoluciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='monto_devolucion_clp',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto de devolucion en CLP'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='monto_devolucion_usd',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto de devolucion en USD'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
