# Generated by Django 4.1.3 on 2022-12-03 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDeControlApp', '0019_devolucion_monto_devolucion_clp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='monto_devolucion_clp',
            field=models.PositiveIntegerField(verbose_name='Monto de devolucion en CLP'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='monto_devolucion_usd',
            field=models.PositiveIntegerField(verbose_name='Monto de devolucion en USD'),
        ),
    ]
