# Generated by Django 4.1.3 on 2022-12-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDeControlApp', '0020_alter_devolucion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
