# Generated by Django 4.1.3 on 2022-12-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDeControlApp', '0021_alter_devolucion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='monto_devolucion_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de devolucion en USD'),
        ),
    ]
