# Generated by Django 4.1.3 on 2022-12-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDeControlApp', '0027_dolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dolar',
            name='fecha',
        ),
    ]
